### PR TITLE
make it possible to configure docker container via environment variables

### PR DESCRIPTION
**Pull request by rainu**
Make it possible to configure docker container via environment variables
and create example docker-compose file.

FYI: @LeberKleber

### CODE REVIEW

**Review by mko-x — APPROVED** [review]
I tried the changes in my fork: https://github.com/mko-x/server
It is working - pretty easy and nice.

**Comment by orthecreedence** [comment]
Hey, sorry for the lag on merging this. It has been a busy few days at work.

My main concern with this is that there is already an (admittedly undocumented) way of overriding the config variables using the ENV, using the `yaml-env` package and `helpers/config.js`

Those overrides you have in `entrypoint.sh` already exist, and so constructing the entire `config.yaml` file on each load isn't necessary (and makes it necessary to update the default config in two places).

That said, I love the docker-compose stuff and the updates to the Dockerfile itself. If you want to strip the env stuff out of the `entrypoint.sh` script I'll gladly merge.

**Comment by rainu** [comment]
I wish I had seen this before. Actually I had the same idea: I wanted to use my [rainu-env-parser](https://github.com/rainu/env-parser) to build a json object directly from ENV variables. Because I also wanted to prevent to define variables at multiple places. It was such a pain to write all these variables in the shell script :smile: 

So I dropped the ENV stuff out of the script except the **TURTL_APP_SECURE_HASH_SALT**. I thought it should be failed fast if the user does not define such a value. Furthermore I wrote a little documentation how to override configuration values via ENV variables.

**Comment by orthecreedence** [comment]
Perfect! Thanks so much, this is great. Also, the documentation update is greatly appreciated.

**Pull request merged**
